#!/bin/bash
# declare STRING variable

MISSION_NAME="DEV"
VEHICLE_NAME="GRANITE"
DEPLOYMENT_NAME="august-epsi4"
PATH_MISSION="/Users/aleboyer/ARNAUD/SCRIPPS/"

RAW_DATA_FILENAME="MADREtest.dat"
RECORDING_MODE="SD"  # other choise is SD or STREAMING
NB_CHANNEL=8
CHANNELS="t1,t2,s1,s2,c,a1,a2,a3"

PROBE_S1_SN="102"
PROBE_S2_SN="102"
PROBE_T1_SN="0130"
PROBE_T2_SN="0135"
PROBE_C_SN="000"
PROBE_SHEAR_CALFILE="/Users/aleboyer/ARNAUD/SCRIPPS/EPSILOMETER/CALIBRATION/SHEAR_PROBES"

AUX1_NAME="SBE49"
AUX1_SN="0058"
AUX1_CALFILE="SBE49/0058.cal"


MADRE_REV="MADREB.2"
MADRE_SN="0005"

MAP_REV="MAPC.0"
MAP_SN="0004"

FIRMWARE_VERSION="MADRE2.1"
FIRMWARE_SAMPLING="320Hz"
FIRMWARE_ADCshear="unipolar"
FIRMWARE_ADCFPO7="bipolar"
FIRMWARE_ADCcond="count"
FIRMWARE_ADCaccellerometer="unipolar"
FIRMWARE_ADCshearfilt="sinc4"
FIRMWARE_ADCfpo7filt="sinc4"
FIRMWARE_ADCcondfilt="none"
FIRMWARE_ADCaccelfilt="sinc4"

declare PATHS=(`python Python_lib/create_mission_from_bash_mission.py $MISSION_NAME $VEHICLE_NAME $DEPLOYMENT_NAME $PATH_MISSION $MADRE_REV $MADRE_SN $MAP_REV $MAP_SN $FIRMWARE_VERSION $FIRMWARE_SAMPLING $FIRMWARE_ADCshear $FIRMWARE_ADCFPO7 $FIRMWARE_ADCaccellerometer $AUX1_NAME $AUX1_SN $AUX1_CALFILE $PROBE_S1_SN $PROBE_S2_SN $PROBE_T1_SN $PROBE_T2_SN $PROBE_SHEAR_CALFILE $FIRMWARE_ADCshearfilt $FIRMWARE_ADCfpo7filt $FIRMWARE_ADCaccelfilt $NB_CHANNEL $CHANNELS $RECORDING_MODE $PROBE_C_SN $FIRMWARE_ADCcond $FIRMWARE_ADCcondfilt`) 
  
echo ${PATHS[0]}
echo ${PATHS[1]}
echo ${PATHS[2]}
